services:
  visual-test:
    build:
      context: .
      dockerfile: Dockerfile.testing
    volumes:
      - .:/src

      # if we omit this, then the containers node_modules will be
      # linked to the hosts node_modules, due to the above
      # volume definition. We don't want that, since different
      # architectures!
      - /src/node_modules
    # network_mode: host
